export const UPDATE_DATETIME = 'UPDATE_DATETIME'
export const GET_WEATHER = 'GET_WEATHER'
export const GET_WEATHER_SUCCESS = 'GET_WEATHER_SUCCESS'
export const GET_WEATHER_FAILURE = 'GET_WEATHER_FAILURE'